# Generated by Django 2.0.4 on 2018-04-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='1749 Roosevelt Street, Fremont, CA, 94539, USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(default='415-367-8853', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, default='12.971599', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='77.594563', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(default='510-371-5856', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
